apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../.base/sample-app-1
nameSuffix: -acc
namespace: acc
labels:
  - pairs:
      app: sample-app-1-acc
      env: acc
      tenant: acc
    includeSelectors: true
patchesStrategicMerge:
- patch.yaml