apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../.base/sample-app-1
nameSuffix: -dev
namespace: dev
labels:
  - pairs:
      app: sample-app-1-dev
      env: dev
      tenant: dev
    includeSelectors: true
patchesStrategicMerge:
- patch.yaml