apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../.base/sample-app-1
nameSuffix: -prod
namespace: prod
labels:
  - pairs:
      app: sample-app-1-prod
      env: prod
      tenant: prod
    includeSelectors: true
patchesStrategicMerge:
- patch.yaml