apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app-1
  name: sample-app-1
  annotations:
    cluster-name: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-app-1
    spec:
      serviceAccountName: sample-app-1-sa
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command:
        - tail
        - -f
        - /dev/null
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
