apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: permission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sample-app-1-sa
