apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app-1
  name: sample-app-1-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app-1
status:
  loadBalancer: {}
